// <auto-generated />
namespace Hyve.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EntityFieldCleanup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityFieldCleanup));
        
        string IMigrationMetadata.Id
        {
            get { return "201803130332225_EntityFieldCleanup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
